# Copyright (c) Bruno Sales <me@baliestri.dev>. Licensed under the MIT License.
# See the LICENSE file in the project root for full license information.

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[container]
disabled = true

[dotnet]
symbol = '.NET'
version_format = '${raw}'
format = 'via [$symbol($version) ]($style)'

[php]
symbol = ''
format = 'via [$symbol ($version )]($style)'
